# Site settings
title: CLI Project
header-img: img/home-bg.png
email: caroline.shields@amkor.com
copyright_name: cbshields
description: > # this means to ignore newlines until "baseurl:"
  What a learning experience!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cbshields
learn_profile: cbshields
email_username: caroline.shields@amkor.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
